#!/bin/bash
# Initialize workflow state IDs for your Shortcut workspace
# Usage: ./shortcut-init-workflow.sh [workflow-name]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/shortcut-common.sh"

TOKEN="$(shortcut_require_token)"
BASE_URL="https://api.app.shortcut.com/api/v3"
WORKFLOW_NAME="${1:-${SHORTCUT_WORKFLOW_NAME:-Fishtechy}}"
CONFIG_DIR="${SHORTCUT_CONFIG_DIR:-$HOME/.config/shortcut}"
CONFIG_FILE="${SHORTCUT_WORKFLOW_CONFIG:-$CONFIG_DIR/workflow-states}"

mkdir -p "$CONFIG_DIR"

echo "🔍 Fetching workflow states from your Shortcut workspace..."
echo "   Preferred workflow: $WORKFLOW_NAME"
echo

WORKFLOWS=$(curl -s -X GET \
  -H "Content-Type: application/json" \
  -H "Shortcut-Token: $TOKEN" \
  "$BASE_URL/workflows")

SELECTED=$(echo "$WORKFLOWS" | jq --arg name "$WORKFLOW_NAME" -c '.[] | select(.name == $name)')
if [ -z "$SELECTED" ]; then
  echo "❌ Workflow not found: $WORKFLOW_NAME" >&2
  echo "Available workflows:" >&2
  echo "$WORKFLOWS" | jq -r '.[].name' >&2
  exit 1
fi

echo "Available workflow states for $WORKFLOW_NAME:"
echo "$SELECTED" | jq -r '.states[] | "  \(.name): \(.id)"'
echo

WORKFLOW_ID=$(echo "$SELECTED" | jq -r '.id')
STATE_TODO=$(echo "$SELECTED" | jq -r '.states[] | select(.name == "To do") | .id' | head -n1)
STATE_IN_PROGRESS=$(echo "$SELECTED" | jq -r '.states[] | select(.name == "InProgress") | .id' | head -n1)
STATE_DONE=$(echo "$SELECTED" | jq -r '.states[] | select(.name == "Closed") | .id' | head -n1)
STATE_BLOCKED=$(echo "$SELECTED" | jq -r '.states[] | select(.name == "Hold/Blocked") | .id' | head -n1)

cat > "$CONFIG_FILE" <<EOF
# Shortcut workflow state IDs for your workspace
# Generated by shortcut-init-workflow.sh
export SHORTCUT_WORKFLOW_NAME=$(printf '%q' "$WORKFLOW_NAME")
export SHORTCUT_WORKFLOW_ID=$WORKFLOW_ID
export SHORTCUT_STATE_TODO=${STATE_TODO:-500000032}
export SHORTCUT_STATE_IN_PROGRESS=${STATE_IN_PROGRESS:-500000037}
export SHORTCUT_STATE_DONE=${STATE_DONE:-500005693}
export SHORTCUT_STATE_BLOCKED=${STATE_BLOCKED:-500000038}
EOF

echo "✅ Workflow states saved to: $CONFIG_FILE"
echo
echo "Current configuration:"
cat "$CONFIG_FILE"
